export const list = {
  'star': 'सितारा',
  'angel': 'देवदूत',
  'fish': 'मछली',
  'spider web': 'मकड़ी का जाला',
  'duck': 'बत्तख',
  'person': 'व्यक्ति',
  'woman': 'महिला',
  'hamburger': 'हैमबर्गर',
  'bow': 'धनुष',
  'clock': 'घड़ी',
  'purse': 'पर्स',
  'bounce': 'उछाल',
  'moon': 'चांद',
  'airplane': 'विमान',
  'eye': 'आंख',
  'flag': 'झंडा',
  'ghost': 'भूत',
  'beak': 'चोंच',
  'mountain': 'पर्वत',
  'bee': 'मधुमक्खी',
  'face': 'चेहरा',
  'finger': 'उंगली',
  'coin': 'सिक्का',
  'bench': 'बेंच',
  'coat': 'कोट',
  'button': 'बटन',
  'feet': 'पैर का पंजा',
  'camera': 'कैमरा',
  'ring': 'अंगूठी',
  'crab': 'केकड़ा',
  'robot': 'रोबोट',
  'girl': 'लड़की',
  'king': 'राजा',
  'cloud': 'बादल',
  'pencil': 'पेंसिल',
  'cookie': 'कुकी',
  'ice cream cone': 'आइसक्रीम कोन',
  'pen': 'कलम',
  'knee': 'घुटना',
  'jail': 'जेल',
  'desk': 'डेस्क',
  'sun': 'रवि',
  'cheese': 'पनीर',
  'cat': 'बिल्ली',
  'doll': 'गुड़िया',
  'bus': 'बस',
  'tail': 'पूंछ',
  'snail': 'घोंघा',
  'book': 'पुस्तक',
  'snake': 'साँप',
  'Angel': 'देवदूत',
  'Eyeball': 'नेत्रगोलक',
  'Pizza': 'पिज़्ज़ा',
  'Angry': 'गुस्सा',
  'Fireworks': 'पटाखे',
  'Pumpkin': 'कद्दू',
  'Baby': 'बच्चा',
  'Flower': 'फूल',
  'Rainbow': 'इंद्रधनुष',
  'Beard': 'दाढ़ी',
  'Flying saucer': 'उड़न तश्तरी',
  'Recycle': 'रीसायकल',
  'Bible': 'बाइबिल',
  'Giraffe': 'जिराफ़',
  'Sand castle': 'रेत का महल',
  'Bikini': 'बिकिनी',
  'Glasses': 'चश्मा',
  'Snowflake': 'हिमपात का एक खंड',
  'Book': 'पुस्तक',
  'High heel': 'ऊँची एड़ी',
  'Stairs': 'सीढ़ियाँ',
  'Bucket': 'बाल्टी',
  'Ice cream cone': 'आइसक्रीम कोन',
  'Starfish': 'एक प्रकार की मछली जिस को पाँच - सात बाहु के सदृश अंग होते है',
  'Bumble bee': 'भंवरा',
  'Igloo': 'इग्लू',
  'Strawberry': 'स्ट्रॉबेरी',
  'Butterfly': 'तितली',
  'Lady bug': 'लेडी बग',
  'Sun': 'रवि',
  'Camera': 'कैमरा',
  'Lamp': 'दीपक',
  'Tire': 'टायर',
  'Cat': 'बिल्ली',
  'Lion': 'सिंह',
  'Toast': 'टोस्ट',
  'Church': 'चर्च',
  'Mailbox': 'मेलबॉक्स',
  'Toothbrush': 'टूथब्रश',
  'Crayon': 'क्रेयॉन',
  'Night': 'रात',
  'Toothpaste': 'टूथपेस्ट',
  'Dolphin': 'डॉल्फिन',
  'Nose': 'नाक',
  'Truck': 'ट्रक',
  'Egg': 'अंडा',
  'Olympics': 'ओलंपिक',
  'Volleyball': 'वालीबाल',
  'Eiffel Tower': 'एफिल टॉवर',
  'Peanut': 'मूंगफली',
  'Abraham Lincoln': 'अब्राहम लिंकन',
  'Kiss': 'चुम्मा',
  'Brain': 'दिमाग',
  'Kitten': 'बिल्ली का बच्चा',
  'Playground': 'खेल का मैदान',
  'Bubble bath': 'बबल स्नान',
  'Kiwi': 'कीवी',
  'Pumpkin pie': 'कद्दू पाई',
  'Buckle': 'बकसुआ',
  'Lipstick': 'लिपस्टिक',
  'Raindrop': 'बूँद',
  'Bus': 'बस',
  'Lobster': 'झींगा मछली',
  'Robot': 'रोबोट',
  'Car accident': 'कार दुर्घटना',
  'Lollipop': 'चूसने की मिठाई',
  'Sand castle': 'रेत का महल',
  'Castle': 'कैसल',
  'Magnet': 'चुंबक',
  'Slipper': 'चप्पल',
  'Chain saw': 'चैन देखा',
  'Megaphone': 'दूर तक शब्द ले जाने का एक प्रकार का यंत्र',
  'Snowball': 'स्नोबॉल',
  'Circus tent': 'सरकस का तंबू',
  'Mermaid': 'मत्स्यांगना',
  'Sprinkler': 'बुझानेवाला',
  'Computer': 'संगणक',
  'Minivan': 'मिनीवैन',
  'Statue of Liberty': 'स्टेचू ऑफ़ लिबर्टी',
  'Crib': 'पालना',
  'Mount Rushmore': 'माउंट रशमोर',
  'Tadpole': 'मेढक का डिंभकीट',
  'Dragon': 'अजगर',
  'Music': 'संगीत',
  'Teepee': 'teepee',
  'Dumbbell': 'डम्बल',
  'North pole': 'उत्तरी ध्रुव',
  'Telescope': 'दूरबीन',
  'Eel': 'बाम मछली',
  'Nurse': 'नर्स',
  'Train': 'रेल गाडी',
  'Ferris wheel': 'बड़ा चक्का',
  'Owl': 'उल्लू',
  'Flag': 'झंडा',
  'Pacifier': 'दिलासा देनेवाला',
  'Tutu': 'टूटू',
  'Junk mail': 'जंक मेल',
  'Piano': 'पियानो',
  'Attic': 'अटारी',
  'Glue': 'गोंद',
  'Pocket watch': 'जेब घड़ी',
  'Back seat': 'पीछे की सीट',
  'Highchair': 'ऊँची कुर्सी',
  'Rock band': 'रॉक बैंड',
  'Birthday': 'जन्मदिन',
  'Hockey': 'हॉकी',
  'Black hole': 'ब्लैक होल',
  'Hotel': 'होटल',
  'Scrambled eggs': 'तले हुए अंडे',
  'Blizzard': 'बर्फानी तूफान',
  'Jump rope': 'रस्सी कूदना',
  'Seat belt': 'सीट बेल्ट',
  'Burrito': 'बरिटो',
  'Koala': 'कोअला',
  'Skip': 'छोड़ें',
  'Captain': 'कप्तान',
  'Leprechaun': 'छोटा सा आदमी',
  'Solar eclipse': 'सूर्य ग्रहण',
  'Chandelier': 'झूमर',
  'Light': 'रोशनी',
  'Space': 'अंतरिक्ष',
  'Crib': 'पालना',
  'Mask': 'मुखौटा',
  'Stethoscope': 'परिश्रावक',
  'Cruise ship': 'क्रूज जहाज',
  'Mechanic': 'मैकेनिक',
  'Stork': 'सारस',
  'Dance': 'नृत्य',
  'Mom': 'माँ',
  'Sunburn': 'धूप की कालिमा',
  'Deodorant': 'डिओडोरेंट',
  'Mr Potato Head': 'मिस्टर मुर्ख',
  'Thread': 'धागा',
  'Facebook': 'फेसबुक',
  'Pantyhose': 'पेंटीहोज',
  'Tourist': 'पर्यटक',
  'Flat': 'समतल',
  'Paper plate': 'कागज की प्लेट',
  'United States': 'संयुक्त राज्य अमेरिका',
  'Frame': 'ढांचा',
  'Photo': 'तस्वीर',
  'WiFi': 'वाई - फाई',
  'Full moon': 'पूर्णचंद्र',
  'Pilgrim': 'यात्री',
  'Zombie': 'ज़ोंबी',
  'Game': 'खेल',
  'Pirate': 'समुद्री डाकू'
}