export const list = {
  'star': 'सितारा',
  'angel': 'देवदूत',
  'fish': 'मछली',
  'spider web': 'मकड़ी का जाला',
  'duck': 'बत्तख',
  'person': 'व्यक्ति',
  'woman': 'महिला',
  'hamburger': 'हैमबर्गर',
  'bow': 'धनुष',
  'clock': 'घड़ी',
  'purse': 'पर्स',
  'bounce': 'उछाल',
  'moon': 'चांद',
  'airplane': 'विमान',
  'eye': 'आंख',
  'flag': 'झंडा',
  'ghost': 'भूत',
  'beak': 'चोंच',
  'mountain': 'पर्वत',
  'bee': 'मधुमक्खी',
  'face': 'चेहरा',
  'finger': 'उंगली',
  'coin': 'सिक्का',
  'bench': 'बेंच',
  'coat': 'कोट',
  'button': 'बटन',
  'feet': 'पैर का पंजा',
  'camera': 'कैमरा',
  'ring': 'अंगूठी',
  'crab': 'केकड़ा',
  'robot': 'रोबोट',
  'girl': 'लड़की',
  'king': 'राजा',
  'cloud': 'बादल',
  'pencil': 'पेंसिल',
  'cookie': 'कुकी',
  'ice cream cone': 'आइसक्रीम कोन',
  'pen': 'कलम',
  'knee': 'घुटना',
  'jail': 'जेल',
  'desk': 'डेस्क',
  'sun': 'रवि',
  'cheese': 'पनीर',
  'cat': 'बिल्ली',
  'doll': 'गुड़िया',
  'bus': 'बस',
  'tail': 'पूंछ',
  'snail': 'घोंघा',
  'book': 'पुस्तक',
  'snake': 'साँप',
}